## Services
google_analytics:
duoshuo: eqielb

## Meta
rss: /atom.xml
favicon: /favicon.jpeg
# icon: /favicon.png
source_url: https://github.com/aiwb/xxx/blob/master/
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  首页: /
  存档: /archives
  电影: /movies
  书籍: /books
  工具: /tools
  链接: /links
  简历: /resume
  关于: /about
  蘑菇街招聘: /recruit
  广告: /shout

right_menus:
  'RSS': /atom.xml
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/aiwb'

## Banners && Widgets
banners:
  markdown: |
    欢迎来到我的博客。

widgets:
  -
    markdown: |
      前端QQ群：71058585.<br>
      我的微信：
      <img style="width: 100%;" src="http://ogl3ykzzi.bkt.clouddn.com/20170303110511_wGClDr_微信二维码.jpeg" alt="吴文斌的微信二维码">
      <div>
        <a href="javascript:;">Linkedin</a>
        <a href="javascript:;">E-mail</a>
        <a href="javascript:;">Weibo</a>
      </div>

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '541330190'
  qun: '71058585'
  v2ex: 'ezreal'
  mobile: '13735851501'
  github: 'aiwb'
  #keybase: 'jysperm'
  zhihu: 'wu-wen-bin-55'
  google_plus: '112906595164862928708'
  segmentfault: 'eaielo'
  twitter: '2wb_x'
  ## https://blockchain.info/zh-cn/wallet/
  bitcoin: '1KTbwSxfLYh6up7KbzZzCa7WJzckC9BhYp'
